protocol = "new-era-continuous-nextgen"
doc = "Daemon for controlling dual syringe pumps with special next generation firmware from New Era."
traits = ["has-position", "is-discrete", "uses-serial", "uses-uart", "is-daemon"]
hardware = ["new-era:dualne1000"]

[links]
source = "https://gitlab.com/yaq/yaqd-new-era"
bugtracker = "https://gitlab.com/yaq/yaqd-new-era/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-new-era"
conda-forge = "https://anaconda.org/conda-forge/yaqd-new-era"

[config]

[config.baud_rate]
default = 19200

[config.identifiers]
default = {"paused" = 0, "pumping"=1}

[state]

[state.position_identifier]
type = "string"
default = "paused"

[state.current_alarm]
type = "string"
default = ""

[state.current_prompt]
type = "string"
default = ""


[messages]

[messages.get_rate]
doc = "Get current rate, in units specified within config."
response = "double"

[messages.set_rate]
doc = "Set current rate, in units specified within config."
request = [{"name"="rate", "type"="double"}]

[messages.set_alarm]
doc = "Disables buzzer if active and sets output IO to LOW."
request = [{"name"="alarm", "type"="boolean"}]


[properties]

[properties.rate]
type = "double"
getter = "get_rate"
setter = "set_rate"
control_kind = "hinted"
record_kind = "metadata"

[properties.alarm]
type="boolean"
getter= "get_alarm"
setter = "set_alarm"
control_kind="hinted"
record_kind="metadata"

